package com.example.mosquizto.Util;

public enum NotificationType {
    COLLECTION_SHARED,
    COLLECTION_REPORTED ,
    JOIN_REQUEST_RECEIVED,
    JOIN_REQUEST_APPROVED,
    JOIN_REQUEST_DENIED,
    HAS_FOLLOWER ,
    USER_REPORTED,
    COLLECTION_CREATED
}
